id: I4E75E6ED
legacy_id: P006638
ocr_import_info:
  bdrc_scan_id: W15274
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T12:04:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:45:56.826610+00:00'
last_modified: 2022-08-30 22:46:44.106985
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W15274
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW15274
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་འགྲེལ་རིགས་མཛོད་ཆེན་མོ།
  author: འུ་ཡུག་པ་བསོད་ནམས་སེངྒེ
statistics:
  ocr_word_mean_confidence_index: 0.5943660776353153
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I2484:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2484
      total_pages: 408
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2484.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6017594785418107
    legacy_id: v002
  I2483:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2483
      total_pages: 406
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2483.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5873833929665744
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
