id: I4E75E6ED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:06:53+00:00'
last_modified: '2022-06-08T05:48:11.980184+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15274
  title: ཚད་མ་རྣམ་འགྲེལ་རིགས་མཛོད་ཆེན་མོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C092:
      image_group_id: I2483
      title: ''
      total_pages: 406
      order: 1
      base_file: C092.txt
    D12D:
      image_group_id: I2484
      title: ''
      total_pages: 408
      order: 2
      base_file: D12D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
